### ISSUE TITLE
MySQL 5.6 supports fulltext indexes w/InnoDB

### ISSUE THREAD

**Issue by morgo** [ServerPress/innodb-autoconvert#1]
This code is needs to be wrapped in version specific detection (or made obsolete):
https://github.com/ServerPress/innodb-autoconvert/blob/master/prepend.php#L35-L54

**Comment by Steveorevo** [comment]
MySQL 5.6 is enforced by context; it should not be possible to run this plugin on DesktopServer versions less than 3.8 (which includes MySQL 5.6). Is there another scenario where this could happen?

**Comment by morgo** [comment]
The only other scenario I can think of is spatial indexes are not supported in InnoDB until MySQL 5.7.  But if your minimum supported version is 5.6, you're free to delete the lines I mentioned.

**Comment by Steveorevo** [comment]
Wouldn't deleting the lines prevent a MyISAM table from converting to InnoDB if they have full text indexes?

**Comment by morgo** [comment]
InnoDB supports fulltext from 5.6.  Hence the issue title :)

**Comment by Steveorevo** [comment]
Ahhh. Yes. The presence of fulltext should no longer cause a conversion error with 5.6. Verifying. Thank you for your feedback!
