### ISSUE TITLE
Innodb Autoconvert plugin is preventing Dynamic Blueprints from working 

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/innodb-autoconvert#2]
#### STEPS TO REPRODUCE: 
1. Have the InnoDB Auto convert plugin active
2. Use a Dynamic blueprint to create the site

#### RESULT: 
The command in the blueprint are not executed due to an exception:
[Thu Oct 26 21:55:57.699416 2017] [php7:error] [pid 51190] [client 127.0.0.1:63691] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Applications/DesktopServer/ds-plugins/innodb-autoconvert/prepend.php:26\nStack trace:\n#0 /Applications/DesktopServer/ds-plugins/innodb-autoconvert/prepend.php(26): PDO-&gt;__construct('mysql:host=loca...', 'test4DB7v5b8', '3kQzFn1JrO')\n#1 /Applications/DesktopServer/runtime/platform/all/ds_runtime.php(143): include_once('/Applications/D...')\n#2 /Applications/DesktopServer/runtime/platform/all/ds_runtime.php(225): DS_Runtime-&gt;processPrepends()\n#3 /Applications/DesktopServer/runtime/platform/all/prepend.php(3): require_once('/Applications/D...')\n#4 {main}\n  thrown in /Applications/DesktopServer/ds-plugins/innodb-autoconvert/prepend.php on line 26

#### EXPECTED RESULT: 
No exception and site is created.

**Comment by davejesch** [comment]
Can verify fix by reproducing error and see that no exception is being logged in the debug.log file.

**Comment by GreggFranklin** [comment]
This issue is resolved
